name: Publish UI to Vercel

env:
  gha-production: ${{ github.ref_name == 'main' }}
  gha-domain: ${{ github.ref_name == 'main' && secrets.DOMAIN_PROD_SCHEMA || secrets.DOMAIN_PREVIEW_SCHEMA }}

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install older version of Vercel CLI until this issue is fixed
      # https://github.com/BetaHuhn/deploy-to-vercel-action/issues/393
      - name: Install Vercel CLI
        run: npm install -g vercel@22.0.1

      - name: Deploy to Vercel
        uses: BetaHuhn/deploy-to-vercel-action@v1.10.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_SCHEMA }}
          VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
          ALIAS_DOMAINS: ${{ env.gha-domain }}
          PRODUCTION: ${{ env.gha-production }}
          FORCE: true
